SimpleCrud/urls.py
from django.contrib import admin
from django.urls import path,include
# from django.urls.conf import include
from crud.views import IndexView
import crud.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',IndexView.as_view()),
    path('crud/',include(('crud.urls','crud'),namespace='crudz'))
    ]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from crud.views import IndexView,CrudDeleteView,ListView,CrudCreateView,CrudUpdateView, DetailsViewSet

router = routers.DefaultRouter()
router.register('sample',DetailsViewSet)

urlpatterns = [
    
    
    path('list/', ListView.as_view(),name='home'),
    path('<pk>/delete',CrudDeleteView.as_view(),name='crud_delete'),
    path('create',CrudCreateView.as_view(),name='crud_create'),
    path('<pk>/edit',CrudUpdateView.as_view(),name='crud_update'),
    path('',include(router.urls))
    ]

crud/models.py
from django.db import models

# Create your models here.

class Details(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return self.first_name

    

simple_app/models.py
from django.db import models

# Create your models here.

crud/forms.py
from django import forms
from crud.models import Details

class CrudCreateForm(forms.ModelForm):
    class Meta:
        model = Details
        fields = '__all__'

        

class CrudUpdateForm(forms.ModelForm):
    class Meta:
        model = Details
        fields = '__all__'
   

crud/views.py
from django.shortcuts import render,redirect
from django.views.generic import View, TemplateView, ListView
from django.views.generic.edit import DeleteView,CreateView,UpdateView
from crud.models import Details

from django.db import IntegrityError
from . import forms
from django.http import JsonResponse
from rest_framework import viewsets
from .serializers import DetailsSerializer
# Create your views here.

# the liat view
class ListView(TemplateView):
    template_name = 'list.html'

    def get_context_data(self,**kwargs):
        context = super(ListView,self).get_context_data(**kwargs)
        context['insert_me'] = Details.objects.all()
        return context

# crud deleteview
# class CrudDeleteView(DeleteView):
#     model = Details

#     def get(self, request, *args, **kwargs):
#         # with transaction.atomic():
#             try:
#                 object = self.get_object()
#                 if object.delete():
#                     response = {
#                         'success': 'Record has been deleted successfully',
#                     }
#                 else:
#                     response = {
#                         'error': 'Record could not be deleted',
#                     }

#             except IntegrityError:
#                 response = {
#                     'error': 'Deleting this Record has been restricted. Please contact your administrator',
#                 }
#             return JsonResponse(response)

class CrudDeleteView(DeleteView):
    model = Details

    def get(self, request, *args, **kwargs):
        # with transaction.atomic():
            try:
                object = self.get_object()
                if object.delete():
                   return redirect('crudz:home')
                else:
                    return redirect('crudz:home')

            except IntegrityError:
                response = {
                    'error': 'Deleting this Record has been restricted. Please contact your administrator',
                }
            return JsonResponse(response)


# template view
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context = super(IndexView,self).get_context_data(**kwargs)
        context['insert_me'] = Details.objects.all()
        return context

# the create view
class CrudCreateView(CreateView):
    form_class = forms.CrudCreateForm
    template_name = 'add.html'

    def form_valid(self, form):
        b = form.save(commit=False)
        b.createhostpc = self.request.META.get('COMPUTERNAME')
        b.userid = self.request.user
        b.save()

        if b:
            return redirect('/crud/list')
        else:
            """If the form is invalid, render the invalid form."""
            return self.render_to_response(self.get_context_data(form=form))
        
    def form_invalid(self, form):
        return self.form_invalid(form=form)

# update view
class CrudUpdateView(UpdateView):
    model = Details
    form_class = forms.CrudUpdateForm
    template_name = 'edit.html'

    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('/crud/list')



#  viewset
class DetailsViewSet(viewsets.ModelViewSet):
    serializer_class = DetailsSerializer
    queryset = Details.objects.all()

simple_app/views.py
from django.shortcuts import render

# Create your views here.

templates/add.html
<!DOCTYPE html>

<html lang="en">
<head>
     <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My first from scratch with django</title>
</head>
<body>
 
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <a href="{% url 'crudz:home' %}" class="waves-effect waves-light btn">Cancel</a>
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
              </button>
        </form>
    </div>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>      
</body>
</html>

templates/delete.html
<!DOCTYPE html>
<html>
   <head>
      <title></title>
   </head>
   <body>
      <form method="post">{% csrf_token %}
         <p>Are you sure you want to delete "{{ object }}"?</p>
         <input type="submit" value="Confirm">
      </form>
   </body>
</html>

templates/edit.html
<!DOCTYPE html>

<html lang="en">
<head>
     <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My first from scratch with django</title>
</head>
<body>
 
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <a href="{% url 'crudz:home' %}" class="waves-effect waves-light btn">Cancel</a>
            <button class="btn waves-effect waves-light" type="submit" name="action">Update
                <i class="material-icons right">send</i>
              </button>
        </form>
    </div>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>      
</body>
</html>

templates/index.html
<!DOCTYPE html>

<html lang="en">
<head>
     <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My first from scratch with django</title>
</head>
<body>
 
    <div class="container">
       
        <h2>Hello there, this is an index page</h2>
        <a href =" {% url 'crudz:home' %}" class="waves-effect waves-light btn-large">Go to List</a>
    </div>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>      
</body>
</html>

templates/list.html
<!DOCTYPE html>

<html lang="en">
<head>
     <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My first from scratch with django</title>
</head>
<body>
 
    <div class="container">
       
        <a href={% url 'crudz:crud_create' %} class="btn-floating btn-large waves-effect waves-light green"><i class="material-icons">add</i></a>
        <table class="striped">
            <thead>
                <tr>
                    <th>First Name
                    </th>
                    <th>Last Name
                    </th>
                    <th>Action
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for i in insert_me %}
                <tr>
                    <td>{{i.first_name}}</td>
                    <td>{{i.last_name}}</td>
                    <td>
                        <a href={% url 'crudz:crud_update' i.id %}><i class="material-icons">edit</i></a>
                        <a href={% url 'crudz:crud_delete' i.id %}><i class="material-icons">delete</i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>      
</body>
</html>